config/routes.rb
Gangstatz::Application.routes.draw do



  match "/charts" => "logs#charts"
  root :to => "logs#index"



  # first created -> highest priority.

  # Sample of regular route:
  #   match 'products/:id' => 'catalog#view'
  # Keep in mind you can assign values other than :controller and :action

  # Sample of named route:
  #   match 'products/:id/purchase' => 'catalog#purchase', :as => :purchase
  # This route can be invoked with purchase_url(:id => product.id)

  # Sample resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Sample resource route with options:
  #   resources :products do
  #     member do
  #       get :short
  #       post :toggle
  #     end
  #
  #     collection do
  #       get :sold
  #     end
  #   end

  # Sample resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Sample resource route with more complex sub-resources
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get :recent, :on => :collection
  #     end
  #   end

  # Sample resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end

  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id(.:format)))'
end

app/models/eightball_log.rb
class EightballLog < ActiveRecord::Base
  belongs_to :nick
end

app/models/link.rb
class Link < ActiveRecord::Base
  belongs_to :nick
end

app/models/log.rb
class Log < ActiveRecord::Base
  belongs_to :nick

  def self.random
    Log.find_by_id(rand(Log.count)) 
  end
  
  def self.hash_by_month
    Log.select(" date_trunc('month', logs.created_at), count(logs.id)").group("date_trunc('month', logs.created_at)").order("date_trunc('month', logs.created_at)").count
  end

end

app/models/nick.rb
class Nick < ActiveRecord::Base
  has_many :logs
  has_many :links
  has_many :eightball_logs

  def wordsies
    log = Log.find(:last, :select => "SUM( LENGTH(text) - LENGTH(REPLACE(text, ' ', ''))+1) AS wordsies", :conditions => "nick_id = '#{self.id}'")
    log.wordsies
  end
  
  def self.active_last(time_period)
    Nick.where("updated_at > '#{time_period.ago}'").count
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :time_taken

  def time_taken
    @time_taken = Time.now
  end
end

app/controllers/logs_controller.rb
class LogsController < ApplicationController
  # GET /logs
  # GET /logs.xml
  def index

    @links = Link.order('id DESC').limit(10)
    @total_count = Log.count
    @sorted_g_logs = Log.group(:nick_id).order("count DESC").select('COUNT(*) AS count, nick_id')
    @nicks = Nick.all
    @eightball = EightballLog.order("id DESC")
    @eightball_limit = @eightball.limit(10)
  end

  def links
    @links_all = Link.find(:all)
    @links = []
    @ids = []
    @links_all.each do |l|
      if l.link["youtube"]
        @links << l
      end

    end
  end

  def show
    @logs = Log.find(:all, :order => "id DESC", :limit => 10000)
  end

  def charts
    @sorted_g_logs = Log.group(:nick_id).order("count DESC").select('COUNT(*) AS count, nick_id')
    @total_count = Log.count
  end


end

app/controllers/nicks_controller.rb
class NicksController < ApplicationController
  # GET /nicks
  # GET /nicks.xml
  def index
    @nicks = Nick.all

    respond_to do |format|
      format.html # index.html.erb
    end
  end

  # GET /nicks/1
  # GET /nicks/1.xml
  def show
    @nick = Nick.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>ntnugangstaz @ efnet</title>
    <meta charset="utf-8">
    <%= javascript_include_tag 'jquery' %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_include_tag 'highcharts/highcharts' %>
    <%= javascript_include_tag 'highcharts/themes/gray' %>
    <%= stylesheet_link_tag 'stylesheet' %>
  </head>
  <body>
    <div id="container">
      <header>
      <img src="/images/gangstatz.png" class="snurr">
      <ul id="nav">
        <li><%= link_to :home, root_path %></li>
        <li><%= link_to :charts, charts_path %></li>
      </ul>
      </header>

      <div id="content">
        <p>Statistics for #ntnugangstaz @ EFNet was generated on <%= Time.now %>. Stats have been generated for <%= time_ago_in_words(Log.first.created_at) %>, and in that period a total of <%= Nick.count %> nicks have been active and <%= Log.count %> lines have been written.</p>
        <%= yield %>
      </div>  

      <footer>
      <p>Gangstatz was created by dagingaa and larsivsi in May 2010. It is currently under development, and any information on this page is prone to error because of it. Logging is done by gangbot written by larsivsi, and presentation made possible by Ruby on Rails written by dagingaa. Yes, that's right haters, I coded Rails all by my self. So STFU.</p>
      <p>Time taken to render page <%= Time.now - @time_taken %></p>
      <p>Source: <a href="https://github.com/dagingaa/ntnugangstatz">github</a></p>
      </footer>
    </div>
  </body>
</html>

app/views/logs/charts.html.erb
<!-- CHARTS -->
<h2>Charts</h2>
<div id="charts">
  <script type="text/javascript"> 

    var chart;
    $(document).ready(function() {
        chart = new Highcharts.Chart({
          chart: {
            renderTo: 'cake',
            plotBackgroundColor: null,
            plotBorderWidth: null,
            plotShadow: false
          },
          title: {
            text: 'Top 5 all time'
          },
          tooltip: {
            formatter: function() {
              return '<b>'+ this.point.name +'</b>: '+ this.y +' %';
            }
          },
          plotOptions: {
            pie: {
              allowPointSelect: true,
              cursor: 'pointer',
              dataLabels: {
                enabled: false
              },
              showInLegend: true
            }
          },
          series: [{
            type: 'pie',
            name: 'User share',
            data: [
              <% count = 1 %>
              <% total_percentage = 0 %>
              <% @sorted_g_logs.each do |t| %>
                ['<%= t.nick.nick %>',<%= percentage = sprintf("%.1f",((t.count.to_f / @total_count.to_f) * 100)) %>], 
                <% total_percentage += percentage.to_f %>
                <% break if count > 4 %>
                <% count += 1 %>
              <% end %>
              ['Others',   <%= 100.0 - total_percentage %>]
            ]
          }]
        });
      });
</script>                                         
<!-- top 5 last month -->
  <script type="text/javascript"> 

    var chart;
    $(document).ready(function() {
        chart = new Highcharts.Chart({
          chart: {
            renderTo: 'cake_month',
            plotBackgroundColor: null,
            plotBorderWidth: null,
            plotShadow: false
          },
          title: {
            text: 'Top 5 last 30 days'
          },
          tooltip: {
            formatter: function() {
              return '<b>'+ this.point.name +'</b>: '+ this.y +' %';
            }
          },
          plotOptions: {
            pie: {
              allowPointSelect: true,
              cursor: 'pointer',
              dataLabels: {
                enabled: false
              },
              showInLegend: true
            }
          },
          series: [{
            type: 'pie',
            name: 'User share',
            data: [
              <% count = 1 %>
              <% total_percentage = 0 %>
              <% @sorted_g_logs.where("created_at > '#{30.days.ago}'").each do |t| %>
                ['<%= t.nick.nick %>',<%= percentage = sprintf("%.1f",((t.count.to_f / Log.where("created_at > '#{30.days.ago}'").count.to_f) * 100)) %>], 
                <% total_percentage += percentage.to_f %>
                <% break if count > 4 %>
                <% count += 1 %>
              <% end %>
              ['Others',   <%= 100.0 - total_percentage %>]
            ]
          }]
        });
      });
</script>                                         


<!-- number of lines per month -->
<% log_months = Log.hash_by_month %>
<script type="text/javascript">
  var chart;
  $(document).ready(function() {
    chart = new Highcharts.Chart({
      chart: {
        renderTo: 'plot',
        defailtSeriesType: 'line',
        //marginRight: 130,
        marginBottom: 25
      },
      title: {
        text: '# lines per month',
        x: -20
      },
      xAxis: {
        <% count = 0 %>
        categories: [
        <% log_months.each do |k,v| %>
          <% count += 1 %>
          <%= count < log_months.size ? "'#{k}', ":"'#{k}'" %>
          <% break unless count < log_months.size-1 %>
        <% end %>
        ]
      },
      yAxis: {
        title: {
          text: '# lines'
        },
        plotLines: [{
          value: 0,
          width: 1,
          color: '#808080'
        }]
      },
      series: [{
        name: 'ntnugangstaz',
        <% count = 0 %>
        data: [
        <% log_months.each do |k,v| %>
          <% count += 1 %>
          <%= count < log_months.size ? "#{v}, ":"'#{v}'" %>
          <% break unless count < log_months.size-1 %>
        <% end %>
        ]
      }]
    });
  });
</script>

<!-- chart divs -->
<div id="cake" style="width: 80%; height: 400px;"></div>
<div id="cake_month" style="width: 80%; height: 400px;"></div>
<div id="plot" style="width: 80%; height: 400px;"></div>
</div>

app/views/logs/index.html.erb
<h2>Highscore</h2>
<div id="highscore">
  <table>
    <th>Place</th>
    <th>Nick</th>
    <th>Percentage</th>
    <th>Lines</th>
    <th>Words</th>
    <th>First Seen</th>
    <th>Last Seen</th>
    <% count = 1 %>
    <% @sorted_g_logs.each do |t| %>
      <% if t.nick != nil %>
        <tr>
          <td><%= count %></td>
          <td><%= t.nick.nick %></td>
          <td><%= sprintf("%.1f",((t.count.to_f / @total_count.to_f) * 100)) %>%</td>
          <td><%= t.count %></td>
          <td><%= t.nick.words %></td>
          <td><%= time_ago_in_words(t.nick.created_at) %> ago</td>
          <td><%= time_ago_in_words(t.nick.updated_at) %> ago</td>
        </tr>
        <% count += 1 %>
      <% end %>
    <%end%>
  </table>
</div>

<!-- GENERAL -->
<% count = 0 %>
<div id="general">
  <h2>General stats</h2>
  <table>
    <tr>
      <td>Number of users</td><td><%= @nicks.size %></td>
    </tr>
    <tr>
      <td>Users active in the last 30 days</td><td><%= Nick.active_last(30.days)  %></td>
    </tr>
    <tr>
      <td>Number of lines</td><td><%= Log.count %></td>
    </tr>
    <tr>
      <td>Number of questions asked to gangbot</td><td><%= EightballLog.count %></td>
    </tr>
    <tr>
      <td>% of lines by top 5 nicks</td><td><% for t in 0..5 %><% count += @sorted_g_logs[t].count.to_i %><%end%><%= sprintf("%.1f",((count.to_f / @total_count.to_f) * 100)) %>%</td>
    </tr>
  </table>
</div>
<div id="funsies">
  <h2>Funsies</h2>
  <% random_log = Log.random %>
  <p>
    Quote of the now: &lsaquo;<%=h random_log.nick.nick %>&rsaquo; <%=h random_log.text %><br>
  </p>
  <div id="links">
    <h2>Last <%= @links.all.size %> links posted</h2>
    <table>
      <th>Link</th>
      <th>Original poster</th>
      <th>First posted</th>
      <% @links.each do |l| %>
        <tr>
          <td class="maxlength"><%= link_to l.link, l.link %></td>
          <td><%=h l.nick.nick %></td>
          <td><%=h l.created_at.strftime("%c") %></td>
        </tr>
      <%end%>
    </table>
  </div>
  <div id="8balls">
    <h2>Last <%= @eightball_limit.all.size %> questions asked to gangbot</h2>
    <table>
      <th>Asked by</th>
      <th>Question</th>
      <th>Answer</th>
      <th>Time since</th>
      <% @eightball_limit.each do |e| %>
        <tr>
          <td><%=h e.nick.nick %></td>
          <td><%=h e.query %></td>
          <td><%=h e.answer %></td>
          <td><%=h time_ago_in_words(Time.parse(e.created_at.to_s)) %></td>
        </tr>
      <%end%>
    </table>
  </div>

app/views/logs/links.html.erb
<p>
Here you go, master. <%= @links.count %> links that met your criteria.
</p>
<ul>
<% @links.each do |l| %>
<li><%= link_to l.link, l.link %></li>
<% end %>
</ul>

app/views/logs/show.html.erb
<%= debug @logs %>

app/views/nicks/_nick.html.erb
<div class="user">
  <h2><%= link_to nick.nick, nick_path(nick) %></h2>
  <p>
    <% if nick.name %>
      <b>Nick:</b> <%=h nick.name %>
    <% end %>
  </p>
</div>

app/views/nicks/edit.html.erb
<h1>Editing nick</h1>

<% form_for(@nick) do |f| %>
  <%= f.error_messages %>

  <p>
    <%= f.label :nick %><br />
    <%= f.text_field :nick %>
  </p>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.submit "Update" %>
  </p>
<% end %>

<%= link_to 'Show', @nick %> |
<%= link_to 'Back', nicks_path %>

app/views/nicks/index.html.erb
<h1>Members of ntnuganstaz</h1>


<% for nick in @nicks %>
  <%= render :partial => nick %>
<% end %>

<br />

app/views/nicks/new.html.erb
<h1>New nick</h1>

<% form_for(@nick) do |f| %>
  <%= f.error_messages %>

  <p>
    <%= f.label :nick %><br />
    <%= f.text_field :nick %>
  </p>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.submit "Create" %>
  </p>
<% end %>

<%= link_to 'Back', nicks_path %>

app/views/nicks/show.html.erb
<%= render :partial => @nick %>

<h2>Funsies</h2>
<p>Random quote: <%= @nick.logs[rand(@nick.logs.size)].text %><br>
  <% if @nick.eightball_logs %>
  Random question: <%= @nick.eightball_logs[rand(@nick.eightball_logs.size)].query %><br>
  Number of questions asked to gangbot: <%= @nick.eightball_logs.size %><br>
<% end %>
  Number of lines written: <%= @nick.logs.size %><br>
  Number of links posted: <%= @nick.links.size %><br>
</p>

<%= link_to 'Back', nicks_path %>